# SPDX-FileCopyrightText: 2024-2025 Contributors to the Fedora Project
#
# SPDX-License-Identifier: LGPL-3.0-or-later

"""
Event specification for GitLab "note" event
"""

headers = {
    "host": "w2fm.gridhead.net",
    "user-agent": "GitLab/18.1.0-pre",
    "content-length": "4360",
    "accept": "*/*",
    "accept-encoding": "gzip, br",
    "connection": "keep-alive",
    "content-type": "application/json",
    "x-gitlab-event": "Note Hook",
    "x-gitlab-webhook-uuid": "6ad2dc3a-4d2c-4c6c-86c2-69c5222ad43f",
    "x-gitlab-event-uuid": "9d0cea47-6545-49cb-b93c-f314e08972f9",
    "x-forwarded-for": "34.74.226.35",
    "x-forwarded-proto": "https",
}

body = {
    "object_kind": "note",
    "event_type": "note",
    "user": {
        "id": 16997011,
        "name": "Shounak Dey",
        "username": "sdglitched",
        "avatar_url": "https://secure.gravatar.com/avatar/9458b3a00e2f3f262b05309bd9a43a233c28689e6cbae811b198cd5ee9fb3653?s=80&d=identicon",
        "email": "[REDACTED]",
    },
    "project_id": 69912300,
    "project": {
        "id": 69912300,
        "name": "w2fm-test",
        "description": None,
        "web_url": "https://gitlab.com/sdglitched/w2fm-test",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:sdglitched/w2fm-test.git",
        "git_http_url": "https://gitlab.com/sdglitched/w2fm-test.git",
        "namespace": "Shounak Dey",
        "visibility_level": 0,
        "path_with_namespace": "sdglitched/w2fm-test",
        "default_branch": "main",
        "ci_config_path": "",
        "homepage": "https://gitlab.com/sdglitched/w2fm-test",
        "url": "git@gitlab.com:sdglitched/w2fm-test.git",
        "ssh_url": "git@gitlab.com:sdglitched/w2fm-test.git",
        "http_url": "https://gitlab.com/sdglitched/w2fm-test.git",
    },
    "object_attributes": {
        "author_id": 16997011,
        "change_position": None,
        "commit_id": None,
        "created_at": "2025-05-16 15:14:33 UTC",
        "discussion_id": "c25f541284b7b964862c675c8b477e27a35485d6",
        "id": 2509662111,
        "line_code": None,
        "note": "This is issue comment.",
        "noteable_id": 167465239,
        "noteable_type": "Issue",
        "original_position": None,
        "position": None,
        "project_id": 69912300,
        "resolved_at": None,
        "resolved_by_id": None,
        "resolved_by_push": None,
        "st_diff": None,
        "system": False,
        "type": None,
        "updated_at": "2025-05-16 15:14:33 UTC",
        "updated_by_id": None,
        "description": "This is issue comment.",
        "url": "https://gitlab.com/sdglitched/w2fm-test/-/issues/1#note_2509662111",
        "action": "create",
    },
    "repository": {
        "name": "w2fm-test",
        "url": "git@gitlab.com:sdglitched/w2fm-test.git",
        "description": None,
        "homepage": "https://gitlab.com/sdglitched/w2fm-test",
    },
    "issue": {
        "author_id": 16997011,
        "closed_at": None,
        "confidential": False,
        "created_at": "2025-05-16 15:10:24 UTC",
        "description": "[BODY] Test Issue 1",
        "discussion_locked": None,
        "due_date": None,
        "id": 167465239,
        "iid": 1,
        "last_edited_at": None,
        "last_edited_by_id": None,
        "milestone_id": None,
        "moved_to_id": None,
        "duplicated_to_id": None,
        "project_id": 69912300,
        "relative_position": 513,
        "state_id": 1,
        "time_estimate": 0,
        "title": "[TITLE] Test Issue 1",
        "updated_at": "2025-05-16 15:14:33 UTC",
        "updated_by_id": None,
        "weight": None,
        "health_status": None,
        "type": "Issue",
        "url": "https://gitlab.com/sdglitched/w2fm-test/-/issues/1",
        "total_time_spent": 0,
        "time_change": 0,
        "human_total_time_spent": None,
        "human_time_change": None,
        "human_time_estimate": None,
        "assignee_ids": [16997011],
        "assignee_id": 16997011,
        "labels": [
            {
                "id": 40565189,
                "title": "bug",
                "color": "#d9534f",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565191,
                "title": "confirmed",
                "color": "#d9534f",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565190,
                "title": "critical",
                "color": "#d9534f",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565195,
                "title": "discussion",
                "color": "#428bca",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565192,
                "title": "documentation",
                "color": "#f0ad4e",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565197,
                "title": "enhancement",
                "color": "#5cb85c",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565196,
                "title": "suggestion",
                "color": "#428bca",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565194,
                "title": "support",
                "color": "#f0ad4e",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
        ],
        "state": "opened",
        "severity": "unknown",
        "customer_relations_contacts": [],
    },
}
