# SPDX-FileCopyrightText: 2024-2025 Contributors to the Fedora Project
#
# SPDX-License-Identifier: LGPL-3.0-or-later

"""
Event specification for GitLab "issues" event
"""

headers = {
    "host": "w2fm.gridhead.net",
    "user-agent": "GitLab/18.1.0-pre",
    "content-length": 8172,
    "accept": "*/*",
    "accept-encoding": "gzip, br",
    "connection": "keep-alive",
    "content-type": "application/json",
    "x-gitlab-event": "Merge Request Hook",
    "x-gitlab-webhook-uuid": "9cf056fa-f86c-49bb-93f0-b9e705eee5df",
    "x-gitlab-event-uuid": "ea4bf54d-f330-4702-94e0-dda5ee03a57f",
    "x-forwarded-for": "34.74.226.47",
    "x-forwarded-proto": "https",
}

body = {
    "object_kind": "merge_request",
    "event_type": "merge_request",
    "user": {
        "id": 16997011,
        "name": "Shounak Dey",
        "username": "sdglitched",
        "avatar_url": "https://secure.gravatar.com/avatar/9458b3a00e2f3f262b05309bd9a43a233c28689e6cbae811b198cd5ee9fb3653?s=80&d=identicon",
        "email": "[REDACTED]",
    },
    "project": {
        "id": 69912300,
        "name": "w2fm-test",
        "description": None,
        "web_url": "https://gitlab.com/sdglitched/w2fm-test",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:sdglitched/w2fm-test.git",
        "git_http_url": "https://gitlab.com/sdglitched/w2fm-test.git",
        "namespace": "Shounak Dey",
        "visibility_level": 0,
        "path_with_namespace": "sdglitched/w2fm-test",
        "default_branch": "main",
        "ci_config_path": "",
        "homepage": "https://gitlab.com/sdglitched/w2fm-test",
        "url": "git@gitlab.com:sdglitched/w2fm-test.git",
        "ssh_url": "git@gitlab.com:sdglitched/w2fm-test.git",
        "http_url": "https://gitlab.com/sdglitched/w2fm-test.git",
    },
    "object_attributes": {
        "assignee_id": 16997011,
        "author_id": 16997011,
        "created_at": "2025-05-16 16:04:39 UTC",
        "description": "Testing merge request\n\nSigned-off-by: Shounak Dey <testaddr@testaddr.test>",
        "draft": False,
        "head_pipeline_id": None,
        "id": 384001326,
        "iid": 1,
        "last_edited_at": None,
        "last_edited_by_id": None,
        "merge_commit_sha": None,
        "merge_error": None,
        "merge_params": {"force_remove_source_branch": "0"},
        "merge_status": "can_be_merged",
        "merge_user_id": None,
        "merge_when_pipeline_succeeds": False,
        "milestone_id": None,
        "source_branch": "test-branch",
        "source_project_id": 69912300,
        "state_id": 1,
        "target_branch": "main",
        "target_project_id": 69912300,
        "time_estimate": 0,
        "title": "Test merge request",
        "updated_at": "2025-05-16 16:04:41 UTC",
        "updated_by_id": None,
        "prepared_at": "2025-05-16 16:04:41 UTC",
        "assignee_ids": [16997011],
        "blocking_discussions_resolved": True,
        "detailed_merge_status": "mergeable",
        "first_contribution": True,
        "human_time_change": None,
        "human_time_estimate": None,
        "human_total_time_spent": None,
        "labels": [
            {
                "id": 40565189,
                "title": "bug",
                "color": "#d9534f",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565191,
                "title": "confirmed",
                "color": "#d9534f",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565190,
                "title": "critical",
                "color": "#d9534f",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565195,
                "title": "discussion",
                "color": "#428bca",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565192,
                "title": "documentation",
                "color": "#f0ad4e",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565197,
                "title": "enhancement",
                "color": "#5cb85c",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565196,
                "title": "suggestion",
                "color": "#428bca",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
            {
                "id": 40565194,
                "title": "support",
                "color": "#f0ad4e",
                "project_id": 69912300,
                "created_at": "2025-05-16 15:09:39 UTC",
                "updated_at": "2025-05-16 15:09:39 UTC",
                "template": False,
                "description": None,
                "type": "ProjectLabel",
                "group_id": None,
            },
        ],
        "last_commit": {
            "id": "7aa00b22e26de3efc8270aebc9ee51c40107d4ff",
            "message": "Test commit\n\nSigned-off-by: Shounak Dey <testaddr@testaddr.test>\n",
            "title": "Test commit",
            "timestamp": "2025-05-16T21:24:13+05:30",
            "url": "https://gitlab.com/sdglitched/w2fm-test/-/commit/7aa00b22e26de3efc8270aebc9ee51c40107d4ff",
            "author": {"name": "Shounak Dey", "email": "testaddr@testaddr.test"},
        },
        "reviewer_ids": [16997011],
        "source": {
            "id": 69912300,
            "name": "w2fm-test",
            "description": None,
            "web_url": "https://gitlab.com/sdglitched/w2fm-test",
            "avatar_url": None,
            "git_ssh_url": "git@gitlab.com:sdglitched/w2fm-test.git",
            "git_http_url": "https://gitlab.com/sdglitched/w2fm-test.git",
            "namespace": "Shounak Dey",
            "visibility_level": 0,
            "path_with_namespace": "sdglitched/w2fm-test",
            "default_branch": "main",
            "ci_config_path": "",
            "homepage": "https://gitlab.com/sdglitched/w2fm-test",
            "url": "git@gitlab.com:sdglitched/w2fm-test.git",
            "ssh_url": "git@gitlab.com:sdglitched/w2fm-test.git",
            "http_url": "https://gitlab.com/sdglitched/w2fm-test.git",
        },
        "state": "opened",
        "target": {
            "id": 69912300,
            "name": "w2fm-test",
            "description": None,
            "web_url": "https://gitlab.com/sdglitched/w2fm-test",
            "avatar_url": None,
            "git_ssh_url": "git@gitlab.com:sdglitched/w2fm-test.git",
            "git_http_url": "https://gitlab.com/sdglitched/w2fm-test.git",
            "namespace": "Shounak Dey",
            "visibility_level": 0,
            "path_with_namespace": "sdglitched/w2fm-test",
            "default_branch": "main",
            "ci_config_path": "",
            "homepage": "https://gitlab.com/sdglitched/w2fm-test",
            "url": "git@gitlab.com:sdglitched/w2fm-test.git",
            "ssh_url": "git@gitlab.com:sdglitched/w2fm-test.git",
            "http_url": "https://gitlab.com/sdglitched/w2fm-test.git",
        },
        "time_change": 0,
        "total_time_spent": 0,
        "url": "https://gitlab.com/sdglitched/w2fm-test/-/merge_requests/1",
        "work_in_progress": False,
        "approval_rules": [],
        "action": "approved",
    },
    "labels": [
        {
            "id": 40565189,
            "title": "bug",
            "color": "#d9534f",
            "project_id": 69912300,
            "created_at": "2025-05-16 15:09:39 UTC",
            "updated_at": "2025-05-16 15:09:39 UTC",
            "template": False,
            "description": None,
            "type": "ProjectLabel",
            "group_id": None,
        },
        {
            "id": 40565191,
            "title": "confirmed",
            "color": "#d9534f",
            "project_id": 69912300,
            "created_at": "2025-05-16 15:09:39 UTC",
            "updated_at": "2025-05-16 15:09:39 UTC",
            "template": False,
            "description": None,
            "type": "ProjectLabel",
            "group_id": None,
        },
        {
            "id": 40565190,
            "title": "critical",
            "color": "#d9534f",
            "project_id": 69912300,
            "created_at": "2025-05-16 15:09:39 UTC",
            "updated_at": "2025-05-16 15:09:39 UTC",
            "template": False,
            "description": None,
            "type": "ProjectLabel",
            "group_id": None,
        },
        {
            "id": 40565195,
            "title": "discussion",
            "color": "#428bca",
            "project_id": 69912300,
            "created_at": "2025-05-16 15:09:39 UTC",
            "updated_at": "2025-05-16 15:09:39 UTC",
            "template": False,
            "description": None,
            "type": "ProjectLabel",
            "group_id": None,
        },
        {
            "id": 40565192,
            "title": "documentation",
            "color": "#f0ad4e",
            "project_id": 69912300,
            "created_at": "2025-05-16 15:09:39 UTC",
            "updated_at": "2025-05-16 15:09:39 UTC",
            "template": False,
            "description": None,
            "type": "ProjectLabel",
            "group_id": None,
        },
        {
            "id": 40565197,
            "title": "enhancement",
            "color": "#5cb85c",
            "project_id": 69912300,
            "created_at": "2025-05-16 15:09:39 UTC",
            "updated_at": "2025-05-16 15:09:39 UTC",
            "template": False,
            "description": None,
            "type": "ProjectLabel",
            "group_id": None,
        },
        {
            "id": 40565196,
            "title": "suggestion",
            "color": "#428bca",
            "project_id": 69912300,
            "created_at": "2025-05-16 15:09:39 UTC",
            "updated_at": "2025-05-16 15:09:39 UTC",
            "template": False,
            "description": None,
            "type": "ProjectLabel",
            "group_id": None,
        },
        {
            "id": 40565194,
            "title": "support",
            "color": "#f0ad4e",
            "project_id": 69912300,
            "created_at": "2025-05-16 15:09:39 UTC",
            "updated_at": "2025-05-16 15:09:39 UTC",
            "template": False,
            "description": None,
            "type": "ProjectLabel",
            "group_id": None,
        },
    ],
    "changes": {},
    "repository": {
        "name": "w2fm-test",
        "url": "git@gitlab.com:sdglitched/w2fm-test.git",
        "description": None,
        "homepage": "https://gitlab.com/sdglitched/w2fm-test",
    },
    "assignees": [
        {
            "id": 16997011,
            "name": "Shounak Dey",
            "username": "sdglitched",
            "avatar_url": "https://secure.gravatar.com/avatar/9458b3a00e2f3f262b05309bd9a43a233c28689e6cbae811b198cd5ee9fb3653?s=80&d=identicon",
            "email": "[REDACTED]",
        }
    ],
    "reviewers": [
        {
            "id": 16997011,
            "name": "Shounak Dey",
            "username": "sdglitched",
            "avatar_url": "https://secure.gravatar.com/avatar/9458b3a00e2f3f262b05309bd9a43a233c28689e6cbae811b198cd5ee9fb3653?s=80&d=identicon",
            "email": "[REDACTED]",
        }
    ],
}
