# SPDX-FileCopyrightText: 2024-2025 Contributors to the Fedora Project
#
# SPDX-License-Identifier: LGPL-3.0-or-later

"""
Event specification for Forgejo "fork" event
"""

headers = {
    "host": "w2fm.gridhead.net",
    "user-agent": "Go-http-client/1.1",
    "content-length": 6815,
    "accept": "*/*",
    "accept-encoding": "gzip",
    "connection": "keep-alive",
    "content-type": "application/json",
    "x-forgejo-event": "push",
    "x-forgejo-delivery": "3a7eee03-a3b4-473e-be5a-9e73f44bc382",
    "x-forwarded-for": "217.197.91.145",
    "x-forwarded-proto": "https",
}

body = {
    "ref": "refs/heads/pull",
    "before": "958064be7bceb13ef5895a2f70d4fa399c5936d1",
    "after": "1c5ccba31592d36a7b999434768c7498edfec822",
    "compare_url": "https://codeberg.org/fedora/w2fm-test/compare/958064be7bceb13ef5895a2f70d4fa399c5936d1...1c5ccba31592d36a7b999434768c7498edfec822",
    "commits": [
        {
            "id": "1c5ccba31592d36a7b999434768c7498edfec822",
            "message": "Taking a dump with `json.dumps()` function\n\nSigned-off-by: Akashdeep Dhar <testuser-w2fm@fedoraproject.org>\n",
            "url": "https://codeberg.org/fedora/w2fm-test/commit/1c5ccba31592d36a7b999434768c7498edfec822",
            "author": {
                "name": "Akashdeep Dhar",
                "email": "testuser-w2fm@fedoraproject.org",
                "username": "gridhead",
            },
            "committer": {
                "name": "Akashdeep Dhar",
                "email": "testuser-w2fm@fedoraproject.org",
                "username": "gridhead",
            },
            "verification": "",
            "timestamp": "2025-04-14T05:25:47Z",
            "added": [],
            "removed": [],
            "modified": ["flsk.py"],
        }
    ],
    "total_commits": 1,
    "head_commit": {
        "id": "1c5ccba31592d36a7b999434768c7498edfec822",
        "message": "Taking a dump with `json.dumps()` function\n\nSigned-off-by: Akashdeep Dhar <testuser-w2fm@fedoraproject.org>\n",
        "url": "https://codeberg.org/fedora/w2fm-test/commit/1c5ccba31592d36a7b999434768c7498edfec822",
        "author": {
            "name": "Akashdeep Dhar",
            "email": "testuser-w2fm@fedoraproject.org",
            "username": "gridhead",
        },
        "committer": {
            "name": "Akashdeep Dhar",
            "email": "testuser-w2fm@fedoraproject.org",
            "username": "gridhead",
        },
        "verification": "",
        "timestamp": "2025-04-14T05:25:47Z",
        "added": [],
        "removed": [],
        "modified": ["flsk.py"],
    },
    "repository": {
        "id": 421133,
        "owner": {
            "id": 95691,
            "login": "fedora",
            "login_name": "",
            "source_id": 0,
            "full_name": "Fedora Project",
            "email": "",
            "avatar_url": "https://codeberg.org/avatars/8ee2d6b067d6e3f045b189a4ea76cd53103749e93ef96f76b61d2aad7ac97e40",
            "html_url": "https://codeberg.org/fedora",
            "language": "",
            "is_admin": False,
            "last_login": "0001-01-01T00:00:00Z",
            "created": "2023-05-06T12:36:00Z",
            "restricted": False,
            "active": False,
            "prohibit_login": False,
            "location": "",
            "pronouns": "",
            "website": "https://fedoraproject.org/",
            "description": "Fedora Project Space",
            "visibility": "public",
            "followers_count": 10,
            "following_count": 0,
            "starred_repos_count": 0,
            "username": "fedora",
        },
        "name": "w2fm-test",
        "full_name": "fedora/w2fm-test",
        "description": "Testing repository of Forgejo Support for Webhook To Fedora Messaging",
        "empty": False,
        "private": False,
        "fork": False,
        "template": False,
        "parent": "",
        "mirror": False,
        "size": 50,
        "language": "",
        "languages_url": "https://codeberg.org/api/v1/repos/fedora/w2fm-test/languages",
        "html_url": "https://codeberg.org/fedora/w2fm-test",
        "url": "https://codeberg.org/api/v1/repos/fedora/w2fm-test",
        "link": "",
        "ssh_url": "git@codeberg.org:fedora/w2fm-test.git",
        "clone_url": "https://codeberg.org/fedora/w2fm-test.git",
        "original_url": "",
        "website": "",
        "stars_count": 0,
        "forks_count": 1,
        "watchers_count": 12,
        "open_issues_count": 2,
        "open_pr_counter": 0,
        "release_counter": 0,
        "default_branch": "main",
        "archived": False,
        "created_at": "2025-04-08T08:58:50Z",
        "updated_at": "2025-04-14T05:29:23Z",
        "archived_at": "1970-01-01T00:00:00Z",
        "permissions": {"admin": True, "push": True, "pull": True},
        "has_issues": True,
        "internal_tracker": {
            "enable_time_tracker": True,
            "allow_only_contributors_to_track_time": True,
            "enable_issue_dependencies": True,
        },
        "has_wiki": False,
        "wiki_branch": "main",
        "globally_editable_wiki": False,
        "has_pull_requests": True,
        "has_projects": False,
        "has_releases": False,
        "has_packages": False,
        "has_actions": False,
        "ignore_whitespace_conflicts": False,
        "allow_merge_commits": True,
        "allow_rebase": True,
        "allow_rebase_explicit": True,
        "allow_squash_merge": True,
        "allow_fast_forward_only_merge": True,
        "allow_rebase_update": True,
        "default_delete_branch_after_merge": False,
        "default_merge_style": "merge",
        "default_allow_maintainer_edit": False,
        "default_update_style": "merge",
        "avatar_url": "",
        "internal": False,
        "mirror_interval": "",
        "object_format_name": "sha1",
        "mirror_updated": "0001-01-01T00:00:00Z",
        "repo_transfer": "",
        "topics": "",
    },
    "pusher": {
        "id": 262265,
        "login": "gridhead",
        "login_name": "",
        "source_id": 0,
        "full_name": "Akashdeep Dhar",
        "email": "gridhead@noreply.codeberg.org",
        "avatar_url": "https://codeberg.org/avatars/0ceeb8e5004de3aa16a074f2936f8bf4047de08ad9db934877ae9e1b2d0530f7",
        "html_url": "https://codeberg.org/gridhead",
        "language": "",
        "is_admin": False,
        "last_login": "0001-01-01T00:00:00Z",
        "created": "2025-01-21T11:12:28Z",
        "restricted": False,
        "active": False,
        "prohibit_login": False,
        "location": "127.0.0.1",
        "pronouns": "he/him",
        "website": "https://gridhead.net/",
        "description": "Akashdeep Dhar is a software engineer in the Red Hat Community Linux Engineering team, working on researching and developing applications running on Fedora InfrasTruecture, and has served twice in Fedora Council.",
        "visibility": "public",
        "followers_count": 0,
        "following_count": 0,
        "starred_repos_count": 0,
        "username": "gridhead",
    },
    "sender": {
        "id": 262265,
        "login": "gridhead",
        "login_name": "",
        "source_id": 0,
        "full_name": "Akashdeep Dhar",
        "email": "gridhead@noreply.codeberg.org",
        "avatar_url": "https://codeberg.org/avatars/0ceeb8e5004de3aa16a074f2936f8bf4047de08ad9db934877ae9e1b2d0530f7",
        "html_url": "https://codeberg.org/gridhead",
        "language": "",
        "is_admin": False,
        "last_login": "0001-01-01T00:00:00Z",
        "created": "2025-01-21T11:12:28Z",
        "restricted": False,
        "active": False,
        "prohibit_login": False,
        "location": "127.0.0.1",
        "pronouns": "he/him",
        "website": "https://gridhead.net/",
        "description": "Akashdeep Dhar is a software engineer in the Red Hat Community Linux Engineering team, working on researching and developing applications running on Fedora InfrasTruecture, and has served twice in Fedora Council.",
        "visibility": "public",
        "followers_count": 0,
        "following_count": 0,
        "starred_repos_count": 0,
        "username": "gridhead",
    },
}
